from tkinter import *
root=Tk()
root.title('Login app')
root.geometry('400x400')
frame=Frame(master=root,height=200,width=360,bg="#cdeeff")
label=Label(frame,text='Full Name',bg="#3895D3",fg="white",width=12)
label2=Label(frame,text='Email ID',bg="#3895D3",fg="white",width=12)
label3=Label(frame,text='Password',bg="#3895D3",fg="white",width=12)
name_entry=Entry(frame)
email_entry=Entry(frame)
password_entry=Entry(frame,show='*')
def display():
    name=name_entry.get()
    greet='Hey '+name
    message="\nCongratulations on creating your new account"
    text_box.insert(END,greet)
    text_box.insert(END,message)
text_box=Text(bg="#BEBEBE",fg="black")
btn=Button(text="Create Account",command=display,bg="#D30808")
frame.place(x=20,y=0)
label.place(x=20,y=20)
name_entry.place(x=150,y=20)
label2.place(x=20,y=80)
email_entry.place(x=150,y=80)
label3.place(x=20,y=140)
password_entry.place(x=150,y=140)
btn.place(x=130,y=210)
text_box.place(x=250)
root.mainloop()